# -*- coding: utf-8 -*-

################################################################################
## Form generated from reading UI file 'compras.ui'
##
## Created by: Qt User Interface Compiler version 6.8.2
##
## WARNING! All changes made in this file will be lost when recompiling UI file!
################################################################################

from PySide6.QtCore import (QCoreApplication, QDate, QDateTime, QLocale,
    QMetaObject, QObject, QPoint, QRect,
    QSize, QTime, QUrl, Qt)
from PySide6.QtGui import (QBrush, QColor, QConicalGradient, QCursor,
    QFont, QFontDatabase, QGradient, QIcon,
    QImage, QKeySequence, QLinearGradient, QPainter,
    QPalette, QPixmap, QRadialGradient, QTransform)
from PySide6.QtWidgets import (QApplication, QDateEdit, QFrame, QLabel,
    QMainWindow, QPlainTextEdit, QPushButton, QSizePolicy,
    QSpinBox, QStatusBar, QTextEdit, QWidget)

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        if not MainWindow.objectName():
            MainWindow.setObjectName(u"MainWindow")
        MainWindow.resize(800, 600)
        MainWindow.setStyleSheet(u"\n"
"    MainWindow {\n"
"        background-image: url(\"imagenes/fondo.jpg\") background-position: center;\n"
"    }\n"
"   ")
        self.centralwidget = QWidget(MainWindow)
        self.centralwidget.setObjectName(u"centralwidget")
        self.Titulo = QLabel(self.centralwidget)
        self.Titulo.setObjectName(u"Titulo")
        self.Titulo.setGeometry(QRect(0, 10, 800, 60))
        font = QFont()
        font.setFamilies([u"Arial"])
        font.setPointSize(20)
        font.setBold(True)
        self.Titulo.setFont(font)
        self.Titulo.setLayoutDirection(Qt.LeftToRight)
        self.Titulo.setStyleSheet(u"color: white;")
        self.Titulo.setAlignment(Qt.AlignCenter)
        self.te_nombre = QTextEdit(self.centralwidget)
        self.te_nombre.setObjectName(u"te_nombre")
        self.te_nombre.setGeometry(QRect(80, 140, 241, 31))
        self.te_apellido = QTextEdit(self.centralwidget)
        self.te_apellido.setObjectName(u"te_apellido")
        self.te_apellido.setGeometry(QRect(80, 220, 241, 31))
        self.bt_cantidad = QSpinBox(self.centralwidget)
        self.bt_cantidad.setObjectName(u"bt_cantidad")
        self.bt_cantidad.setGeometry(QRect(280, 370, 42, 22))
        self.te_dni = QTextEdit(self.centralwidget)
        self.te_dni.setObjectName(u"te_dni")
        self.te_dni.setGeometry(QRect(80, 310, 241, 31))
        self.boton_comprar = QPushButton(self.centralwidget)
        self.boton_comprar.setObjectName(u"boton_comprar")
        self.boton_comprar.setGeometry(QRect(370, 530, 75, 24))
        self.bt_salida = QDateEdit(self.centralwidget)
        self.bt_salida.setObjectName(u"bt_salida")
        self.bt_salida.setGeometry(QRect(580, 110, 110, 22))
        self.bt_salida.setDateTime(QDateTime(QDate(2025, 2, 24), QTime(0, 0, 0)))
        self.bt_salida.setDate(QDate(2025, 2, 24))
        self.bt_vuelta = QDateEdit(self.centralwidget)
        self.bt_vuelta.setObjectName(u"bt_vuelta")
        self.bt_vuelta.setGeometry(QRect(580, 140, 110, 22))
        self.bt_vuelta.setDateTime(QDateTime(QDate(2025, 2, 24), QTime(23, 0, 0)))
        self.bt_vuelta.setDate(QDate(2025, 2, 24))
        self.plainTextEdit = QPlainTextEdit(self.centralwidget)
        self.plainTextEdit.setObjectName(u"plainTextEdit")
        self.plainTextEdit.setGeometry(QRect(80, 110, 241, 20))
        self.plainTextEdit.setAcceptDrops(True)
        self.plainTextEdit.setFrameShape(QFrame.NoFrame)
        self.plainTextEdit.setFrameShadow(QFrame.Sunken)
        self.plainTextEdit.setVerticalScrollBarPolicy(Qt.ScrollBarAlwaysOff)
        self.plainTextEdit.setHorizontalScrollBarPolicy(Qt.ScrollBarAlwaysOff)
        self.plainTextEdit.setTabChangesFocus(False)
        self.plainTextEdit.setReadOnly(True)
        self.plainTextEdit.setBackgroundVisible(False)
        self.plainTextEdit.setCenterOnScroll(False)
        self.plainTextEdit_2 = QPlainTextEdit(self.centralwidget)
        self.plainTextEdit_2.setObjectName(u"plainTextEdit_2")
        self.plainTextEdit_2.setGeometry(QRect(80, 190, 241, 20))
        self.plainTextEdit_2.setAcceptDrops(True)
        self.plainTextEdit_2.setFrameShape(QFrame.NoFrame)
        self.plainTextEdit_2.setFrameShadow(QFrame.Sunken)
        self.plainTextEdit_2.setVerticalScrollBarPolicy(Qt.ScrollBarAlwaysOff)
        self.plainTextEdit_2.setHorizontalScrollBarPolicy(Qt.ScrollBarAlwaysOff)
        self.plainTextEdit_2.setTabChangesFocus(False)
        self.plainTextEdit_2.setReadOnly(True)
        self.plainTextEdit_2.setBackgroundVisible(False)
        self.plainTextEdit_2.setCenterOnScroll(False)
        self.plainTextEdit_3 = QPlainTextEdit(self.centralwidget)
        self.plainTextEdit_3.setObjectName(u"plainTextEdit_3")
        self.plainTextEdit_3.setGeometry(QRect(80, 280, 241, 20))
        self.plainTextEdit_3.setAcceptDrops(True)
        self.plainTextEdit_3.setFrameShape(QFrame.NoFrame)
        self.plainTextEdit_3.setFrameShadow(QFrame.Sunken)
        self.plainTextEdit_3.setVerticalScrollBarPolicy(Qt.ScrollBarAlwaysOff)
        self.plainTextEdit_3.setHorizontalScrollBarPolicy(Qt.ScrollBarAlwaysOff)
        self.plainTextEdit_3.setTabChangesFocus(False)
        self.plainTextEdit_3.setReadOnly(True)
        self.plainTextEdit_3.setBackgroundVisible(False)
        self.plainTextEdit_3.setCenterOnScroll(False)
        self.plainTextEdit_4 = QPlainTextEdit(self.centralwidget)
        self.plainTextEdit_4.setObjectName(u"plainTextEdit_4")
        self.plainTextEdit_4.setGeometry(QRect(450, 110, 241, 20))
        self.plainTextEdit_4.setAcceptDrops(True)
        self.plainTextEdit_4.setFrameShape(QFrame.NoFrame)
        self.plainTextEdit_4.setFrameShadow(QFrame.Sunken)
        self.plainTextEdit_4.setVerticalScrollBarPolicy(Qt.ScrollBarAlwaysOff)
        self.plainTextEdit_4.setHorizontalScrollBarPolicy(Qt.ScrollBarAlwaysOff)
        self.plainTextEdit_4.setTabChangesFocus(False)
        self.plainTextEdit_4.setReadOnly(True)
        self.plainTextEdit_4.setBackgroundVisible(False)
        self.plainTextEdit_4.setCenterOnScroll(False)
        self.plainTextEdit_5 = QPlainTextEdit(self.centralwidget)
        self.plainTextEdit_5.setObjectName(u"plainTextEdit_5")
        self.plainTextEdit_5.setGeometry(QRect(450, 140, 241, 20))
        self.plainTextEdit_5.setAcceptDrops(True)
        self.plainTextEdit_5.setFrameShape(QFrame.NoFrame)
        self.plainTextEdit_5.setFrameShadow(QFrame.Sunken)
        self.plainTextEdit_5.setVerticalScrollBarPolicy(Qt.ScrollBarAlwaysOff)
        self.plainTextEdit_5.setHorizontalScrollBarPolicy(Qt.ScrollBarAlwaysOff)
        self.plainTextEdit_5.setTabChangesFocus(False)
        self.plainTextEdit_5.setReadOnly(True)
        self.plainTextEdit_5.setBackgroundVisible(False)
        self.plainTextEdit_5.setCenterOnScroll(False)
        self.plainTextEdit_6 = QPlainTextEdit(self.centralwidget)
        self.plainTextEdit_6.setObjectName(u"plainTextEdit_6")
        self.plainTextEdit_6.setGeometry(QRect(80, 370, 241, 20))
        self.plainTextEdit_6.setAcceptDrops(True)
        self.plainTextEdit_6.setFrameShape(QFrame.NoFrame)
        self.plainTextEdit_6.setFrameShadow(QFrame.Sunken)
        self.plainTextEdit_6.setVerticalScrollBarPolicy(Qt.ScrollBarAlwaysOff)
        self.plainTextEdit_6.setHorizontalScrollBarPolicy(Qt.ScrollBarAlwaysOff)
        self.plainTextEdit_6.setTabChangesFocus(False)
        self.plainTextEdit_6.setReadOnly(True)
        self.plainTextEdit_6.setBackgroundVisible(False)
        self.plainTextEdit_6.setCenterOnScroll(False)
        self.pt_destino = QPlainTextEdit(self.centralwidget)
        self.pt_destino.setObjectName(u"pt_destino")
        self.pt_destino.setGeometry(QRect(450, 220, 241, 31))
        self.pt_vuelo = QPlainTextEdit(self.centralwidget)
        self.pt_vuelo.setObjectName(u"pt_vuelo")
        self.pt_vuelo.setGeometry(QRect(450, 310, 241, 31))
        self.plainTextEdit_7 = QPlainTextEdit(self.centralwidget)
        self.plainTextEdit_7.setObjectName(u"plainTextEdit_7")
        self.plainTextEdit_7.setGeometry(QRect(450, 190, 241, 20))
        self.plainTextEdit_7.setAcceptDrops(True)
        self.plainTextEdit_7.setFrameShape(QFrame.NoFrame)
        self.plainTextEdit_7.setFrameShadow(QFrame.Sunken)
        self.plainTextEdit_7.setVerticalScrollBarPolicy(Qt.ScrollBarAlwaysOff)
        self.plainTextEdit_7.setHorizontalScrollBarPolicy(Qt.ScrollBarAlwaysOff)
        self.plainTextEdit_7.setTabChangesFocus(False)
        self.plainTextEdit_7.setReadOnly(True)
        self.plainTextEdit_7.setBackgroundVisible(False)
        self.plainTextEdit_7.setCenterOnScroll(False)
        self.plainTextEdit_8 = QPlainTextEdit(self.centralwidget)
        self.plainTextEdit_8.setObjectName(u"plainTextEdit_8")
        self.plainTextEdit_8.setGeometry(QRect(450, 280, 241, 20))
        self.plainTextEdit_8.setAcceptDrops(True)
        self.plainTextEdit_8.setFrameShape(QFrame.NoFrame)
        self.plainTextEdit_8.setFrameShadow(QFrame.Sunken)
        self.plainTextEdit_8.setVerticalScrollBarPolicy(Qt.ScrollBarAlwaysOff)
        self.plainTextEdit_8.setHorizontalScrollBarPolicy(Qt.ScrollBarAlwaysOff)
        self.plainTextEdit_8.setTabChangesFocus(False)
        self.plainTextEdit_8.setReadOnly(True)
        self.plainTextEdit_8.setBackgroundVisible(False)
        self.plainTextEdit_8.setCenterOnScroll(False)
        MainWindow.setCentralWidget(self.centralwidget)
        self.plainTextEdit_5.raise_()
        self.plainTextEdit_4.raise_()
        self.plainTextEdit_6.raise_()
        self.Titulo.raise_()
        self.te_nombre.raise_()
        self.te_apellido.raise_()
        self.bt_cantidad.raise_()
        self.te_dni.raise_()
        self.boton_comprar.raise_()
        self.bt_salida.raise_()
        self.bt_vuelta.raise_()
        self.plainTextEdit.raise_()
        self.plainTextEdit_2.raise_()
        self.plainTextEdit_3.raise_()
        self.pt_destino.raise_()
        self.pt_vuelo.raise_()
        self.plainTextEdit_7.raise_()
        self.plainTextEdit_8.raise_()
        self.statusbar = QStatusBar(MainWindow)
        self.statusbar.setObjectName(u"statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)

        QMetaObject.connectSlotsByName(MainWindow)
    # setupUi

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(QCoreApplication.translate("MainWindow", u"Vuelos App", None))
        self.Titulo.setText(QCoreApplication.translate("MainWindow", u"COMPRAR VUELO", None))
        self.boton_comprar.setText(QCoreApplication.translate("MainWindow", u"Comprar", None))
        self.plainTextEdit.setPlainText(QCoreApplication.translate("MainWindow", u"Nombre del pasajero", None))
        self.plainTextEdit_2.setPlainText(QCoreApplication.translate("MainWindow", u"Apellido del pasajero", None))
        self.plainTextEdit_3.setPlainText(QCoreApplication.translate("MainWindow", u"DNI del pasajero", None))
        self.plainTextEdit_4.setPlainText(QCoreApplication.translate("MainWindow", u"Fecha de salida", None))
        self.plainTextEdit_5.setPlainText(QCoreApplication.translate("MainWindow", u"Fecha de vuelta", None))
        self.plainTextEdit_6.setPlainText(QCoreApplication.translate("MainWindow", u"Cantidad de asientos", None))
        self.plainTextEdit_7.setPlainText(QCoreApplication.translate("MainWindow", u"Destino del vuelo", None))
        self.plainTextEdit_8.setPlainText(QCoreApplication.translate("MainWindow", u"Avi\u00f3n del vuelo", None))
    # retranslateUi

